/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tenants
         * @description Get paginated list of all tenants on the platform.
         *     Supports filtering by status, plan, etc.
         */
        get: operations["listAllTenants"];
        put?: never;
        /**
         * Create new tenant
         * @description Provision a new tenant for a customer.
         *     This is called during the SaaS signup flow.
         */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tenant details
         * @description Full tenant information including billing and usage
         */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        /**
         * Delete tenant
         * @description Permanently delete a tenant and all associated data.
         *     Requires super_admin role.
         */
        delete: operations["deleteTenant"];
        options?: never;
        head?: never;
        /**
         * Update tenant
         * @description Modify tenant settings (plan, limits, etc.)
         */
        patch: operations["updateTenant"];
        trace?: never;
    };
    "/tenants/{tenantId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend tenant
         * @description Temporarily disable a tenant (e.g., for billing issues)
         */
        post: operations["suspendTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate tenant
         * @description Reactivate a suspended tenant
         */
        post: operations["activateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate tenant database
         * @description Run migrations or schema updates for a specific tenant
         */
        post: operations["migrateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users across all tenants
         * @description Cross-tenant user search for support and compliance.
         *     Requires super_admin role.
         */
        get: operations["searchAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user across tenants
         * @description Get user details including all tenant memberships
         */
        get: operations["getPlatformUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate impersonation token
         * @description Create a temporary JWT to impersonate a user for support purposes.
         *     Requires super_admin role. Action is heavily audited.
         */
        post: operations["impersonateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all subscriptions
         * @description Get all tenant subscriptions for billing dashboard
         */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/tenants/{tenantId}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant subscription */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update tenant subscription
         * @description Change plan, seats, or billing interval
         */
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/billing/tenants/{tenantId}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate invoice
         * @description Generate immediate invoice (for manual billing)
         */
        post: operations["generateInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe/webhook receiver
         * @description Receive and process billing webhooks
         */
        post: operations["billingWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform overview metrics
         * @description High-level SaaS metrics (MRR, churn, etc.)
         */
        get: operations["getPlatformOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant growth analytics
         * @description New tenants, activations, churn over time
         */
        get: operations["getTenantAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform usage metrics
         * @description Aggregated usage across all tenants
         */
        get: operations["getUsageAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feature flags
         * @description Get all platform feature flags
         */
        get: operations["listFeatureFlags"];
        put?: never;
        /** Create feature flag */
        post: operations["createFeatureFlag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/features/{flagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update feature flag
         * @description Enable/disable or modify rollout
         */
        patch: operations["updateFeatureFlag"];
        trace?: never;
    };
    "/config/oauth-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List global OAuth providers
         * @description OAuth providers available platform-wide
         */
        get: operations["listOAuthProviders"];
        put?: never;
        /**
         * Add OAuth provider
         * @description Configure new OAuth provider for all tenants
         */
        post: operations["addOAuthProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run database migrations
         * @description Execute pending migrations across all tenant databases
         */
        post: operations["runMigrations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger backup
         * @description Initiate backup for tenant(s) or entire platform
         */
        post: operations["triggerBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error?: {
                code?: string;
                message?: string;
                details?: Record<string, never>;
            };
        };
        MessageResponse: {
            message?: string;
        };
        PaginationResponse: {
            page?: number;
            perPage?: number;
            total?: number;
            totalPages?: number;
        };
        CreateTenantRequest: {
            /** @description Display name for the tenant */
            name: string;
            /** @description URL-friendly identifier */
            slug: string;
            /**
             * @default free
             * @enum {string}
             */
            plan: "free" | "starter" | "pro" | "enterprise";
            /**
             * Format: email
             * @description Email of the tenant owner
             */
            ownerEmail?: string;
            ownerName?: string;
            /** @description Custom domain for the tenant */
            customDomain?: string;
        };
        UpdateTenantRequest: {
            name?: string;
            /** @enum {string} */
            plan?: "free" | "starter" | "pro" | "enterprise";
            limits?: {
                maxUsers?: number;
                maxOrganizations?: number;
                maxApiCallsPerMonth?: number;
            };
            settings?: {
                allowCustomBranding?: boolean;
                allowSso?: boolean;
                allowApiAccess?: boolean;
            };
        };
        TenantDetailResponse: {
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            status?: "active" | "suspended" | "pending_deletion" | "trial";
            plan?: string;
            customDomain?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            owner?: {
                id?: string;
                email?: string;
                name?: string;
            };
            limits?: {
                maxUsers?: number;
                maxOrganizations?: number;
                maxApiCallsPerMonth?: number;
            };
            usage?: {
                currentUsers?: number;
                currentOrganizations?: number;
                apiCallsThisMonth?: number;
            };
            billing?: {
                subscriptionId?: string;
                status?: string;
                /** Format: date-time */
                currentPeriodStart?: string;
                /** Format: date-time */
                currentPeriodEnd?: string;
            };
        };
        PlatformUserResponse: {
            id?: string;
            email?: string;
            name?: string | null;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            tenantCount?: number;
        };
        PlatformUserDetailResponse: {
            id?: string;
            email?: string;
            name?: string | null;
            emailVerified?: boolean;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
            tenants?: {
                tenantId?: string;
                tenantName?: string;
                tenantSlug?: string;
                role?: string;
                /** Format: date-time */
                joinedAt?: string;
            }[];
            mfaEnabled?: boolean;
            failedLoginAttempts?: number;
        };
        SubscriptionResponse: {
            id?: string;
            tenantId?: string;
            /** @enum {string} */
            status?: "active" | "past_due" | "canceled" | "trialing" | "incomplete";
            plan?: string;
            seats?: number;
            seatsUsed?: number;
            billingInterval?: string;
            /** Format: date-time */
            currentPeriodStart?: string;
            /** Format: date-time */
            currentPeriodEnd?: string;
            cancelAtPeriodEnd?: boolean;
            amount?: {
                currency?: string;
                perSeat?: number;
                total?: number;
            };
        };
        InvoiceResponse: {
            id?: string;
            tenantId?: string;
            status?: string;
            amount?: number;
            currency?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uri */
            pdfUrl?: string;
        };
        PlatformOverviewResponse: {
            tenants?: {
                total?: number;
                active?: number;
                trial?: number;
                newThisMonth?: number;
            };
            users?: {
                total?: number;
                activeToday?: number;
            };
            revenue?: {
                mrr?: number;
                arr?: number;
                currency?: string;
            };
            system?: {
                totalApiCalls24h?: number;
                averageLatency?: number;
                errorRate?: number;
            };
        };
        FeatureFlagResponse: {
            id?: string;
            key?: string;
            name?: string;
            description?: string;
            enabled?: boolean;
            rolloutPercentage?: number;
            allowedTenants?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateFeatureFlagRequest: {
            key: string;
            name: string;
            description?: string;
            /** @default false */
            enabled: boolean;
            /** @default 0 */
            rolloutPercentage: number;
        };
        OAuthProviderConfigResponse: {
            id?: string;
            provider?: string;
            name?: string;
            enabled?: boolean;
            clientId?: string;
            scopes?: string[];
            allowTenantOverride?: boolean;
        };
        OAuthProviderConfigRequest: {
            /** @enum {string} */
            provider: "google" | "github" | "microsoft" | "apple" | "discord" | "slack" | "okta";
            name: string;
            clientId: string;
            clientSecret: string;
            scopes?: string[];
            /** @default true */
            enabled: boolean;
            /** @default true */
            allowTenantOverride: boolean;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description API key missing or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient privileges */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAllTenants: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                status?: "active" | "suspended" | "pending_deletion" | "trial";
                plan?: "free" | "starter" | "pro" | "enterprise";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TenantDetailResponse"][];
                        pagination?: components["schemas"]["PaginationResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTenant: {
        parameters: {
            query?: {
                /** @description Skip grace period and delete immediately */
                force?: boolean;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant scheduled for deletion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    suspendTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                    /** Format: date-time */
                    suspendUntil?: string;
                };
            };
        };
        responses: {
            /** @description Tenant suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetailResponse"];
                };
            };
        };
    };
    activateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDetailResponse"];
                };
            };
        };
    };
    migrateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Target schema version */
                    targetVersion?: string;
                };
            };
        };
        responses: {
            /** @description Migration completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        version?: string;
                        /** @description Duration in milliseconds */
                        duration?: number;
                    };
                };
            };
        };
    };
    searchAllUsers: {
        parameters: {
            query?: {
                /** @description Exact or partial email match */
                email?: string;
                tenantId?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PlatformUserResponse"][];
                        pagination?: components["schemas"]["PaginationResponse"];
                    };
                };
            };
        };
    };
    getPlatformUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details with memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformUserDetailResponse"];
                };
            };
        };
    };
    impersonateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Which tenant context to impersonate in */
                    tenantId?: string;
                    /**
                     * @description Token lifetime in seconds (max 3600)
                     * @default 900
                     */
                    duration?: number;
                    /** @description Reason for impersonation (audited) */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Impersonation token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                        tenantId?: string;
                    };
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: {
                status?: "active" | "past_due" | "canceled" | "trialing";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SubscriptionResponse"][];
                    };
                };
            };
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    plan?: "free" | "starter" | "pro" | "enterprise";
                    seats?: number;
                    /** @enum {string} */
                    billingInterval?: "monthly" | "annual";
                };
            };
        };
        responses: {
            /** @description Subscription updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
        };
    };
    generateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    amount?: number;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Invoice generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
        };
    };
    billingWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlatformOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOverviewResponse"];
                };
            };
        };
    };
    getTenantAnalytics: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                groupBy?: "day" | "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            date?: string;
                            newTenants?: number;
                            activeTenants?: number;
                            churnedTenants?: number;
                        }[];
                    };
                };
            };
        };
    };
    getUsageAnalytics: {
        parameters: {
            query: {
                metric: "activeUsers" | "logins" | "apiCalls" | "storage";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        byTenant?: {
                            tenantId?: string;
                            value?: number;
                        }[];
                    };
                };
            };
        };
    };
    listFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"][];
                };
            };
        };
    };
    createFeatureFlag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeatureFlagRequest"];
            };
        };
        responses: {
            /** @description Feature flag created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"];
                };
            };
        };
    };
    updateFeatureFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flagId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled?: boolean;
                    rolloutPercentage?: number;
                    allowedTenants?: string[];
                };
            };
        };
        responses: {
            /** @description Feature flag updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"];
                };
            };
        };
    };
    listOAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthProviderConfigResponse"][];
                };
            };
        };
    };
    addOAuthProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthProviderConfigRequest"];
            };
        };
        responses: {
            /** @description Provider added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthProviderConfigResponse"];
                };
            };
        };
    };
    runMigrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default true */
                    dryRun?: boolean;
                    targetVersion?: string;
                };
            };
        };
        responses: {
            /** @description Migration results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        results?: {
                            tenantId?: string;
                            status?: string;
                            version?: string;
                        }[];
                    };
                };
            };
        };
    };
    triggerBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Specific tenant, or omit for all */
                    tenantId?: string;
                    /**
                     * @default full
                     * @enum {string}
                     */
                    type?: "full" | "incremental";
                };
            };
        };
        responses: {
            /** @description Backup initiated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobId?: string;
                        status?: string;
                    };
                };
            };
        };
    };
}
