/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as HostedIndexRouteImport } from './routes/hosted/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as TenantsCreateRouteImport } from './routes/tenants/create'
import { Route as TenantsIdRouteImport } from './routes/tenants/$id'
import { Route as SettingsWebhooksRouteImport } from './routes/settings/webhooks'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as HostedVerifyEmailRouteImport } from './routes/hosted/verify-email'
import { Route as HostedSignUpRouteImport } from './routes/hosted/sign-up'
import { Route as HostedSignInRouteImport } from './routes/hosted/sign-in'
import { Route as HostedOauthCallbackRouteImport } from './routes/hosted/oauth-callback'
import { Route as HostedMfaRouteImport } from './routes/hosted/mfa'
import { Route as HostedForgotPasswordRouteImport } from './routes/hosted/forgot-password'
import { Route as HostedOrganizationSwitchRouteImport } from './routes/hosted/organization/switch'
import { Route as HostedOrganizationCreateRouteImport } from './routes/hosted/organization/create'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedIndexRoute = HostedIndexRouteImport.update({
  id: '/hosted/',
  path: '/hosted/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsCreateRoute = TenantsCreateRouteImport.update({
  id: '/tenants/create',
  path: '/tenants/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const HostedVerifyEmailRoute = HostedVerifyEmailRouteImport.update({
  id: '/hosted/verify-email',
  path: '/hosted/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedSignUpRoute = HostedSignUpRouteImport.update({
  id: '/hosted/sign-up',
  path: '/hosted/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedSignInRoute = HostedSignInRouteImport.update({
  id: '/hosted/sign-in',
  path: '/hosted/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedOauthCallbackRoute = HostedOauthCallbackRouteImport.update({
  id: '/hosted/oauth-callback',
  path: '/hosted/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedMfaRoute = HostedMfaRouteImport.update({
  id: '/hosted/mfa',
  path: '/hosted/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedForgotPasswordRoute = HostedForgotPasswordRouteImport.update({
  id: '/hosted/forgot-password',
  path: '/hosted/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedOrganizationSwitchRoute =
  HostedOrganizationSwitchRouteImport.update({
    id: '/hosted/organization/switch',
    path: '/hosted/organization/switch',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostedOrganizationCreateRoute =
  HostedOrganizationCreateRouteImport.update({
    id: '/hosted/organization/create',
    path: '/hosted/organization/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/hosted/forgot-password': typeof HostedForgotPasswordRoute
  '/hosted/mfa': typeof HostedMfaRoute
  '/hosted/oauth-callback': typeof HostedOauthCallbackRoute
  '/hosted/sign-in': typeof HostedSignInRoute
  '/hosted/sign-up': typeof HostedSignUpRoute
  '/hosted/verify-email': typeof HostedVerifyEmailRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/create': typeof TenantsCreateRoute
  '/billing/': typeof BillingIndexRoute
  '/hosted/': typeof HostedIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/hosted/organization/create': typeof HostedOrganizationCreateRoute
  '/hosted/organization/switch': typeof HostedOrganizationSwitchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/hosted/forgot-password': typeof HostedForgotPasswordRoute
  '/hosted/mfa': typeof HostedMfaRoute
  '/hosted/oauth-callback': typeof HostedOauthCallbackRoute
  '/hosted/sign-in': typeof HostedSignInRoute
  '/hosted/sign-up': typeof HostedSignUpRoute
  '/hosted/verify-email': typeof HostedVerifyEmailRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/create': typeof TenantsCreateRoute
  '/billing': typeof BillingIndexRoute
  '/hosted': typeof HostedIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/hosted/organization/create': typeof HostedOrganizationCreateRoute
  '/hosted/organization/switch': typeof HostedOrganizationSwitchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/hosted/forgot-password': typeof HostedForgotPasswordRoute
  '/hosted/mfa': typeof HostedMfaRoute
  '/hosted/oauth-callback': typeof HostedOauthCallbackRoute
  '/hosted/sign-in': typeof HostedSignInRoute
  '/hosted/sign-up': typeof HostedSignUpRoute
  '/hosted/verify-email': typeof HostedVerifyEmailRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/create': typeof TenantsCreateRoute
  '/billing/': typeof BillingIndexRoute
  '/hosted/': typeof HostedIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/hosted/organization/create': typeof HostedOrganizationCreateRoute
  '/hosted/organization/switch': typeof HostedOrganizationSwitchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/login'
    | '/settings'
    | '/users'
    | '/hosted/forgot-password'
    | '/hosted/mfa'
    | '/hosted/oauth-callback'
    | '/hosted/sign-in'
    | '/hosted/sign-up'
    | '/hosted/verify-email'
    | '/settings/security'
    | '/settings/webhooks'
    | '/tenants/$id'
    | '/tenants/create'
    | '/billing/'
    | '/hosted/'
    | '/organizations/'
    | '/tenants/'
    | '/hosted/organization/create'
    | '/hosted/organization/switch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/login'
    | '/settings'
    | '/users'
    | '/hosted/forgot-password'
    | '/hosted/mfa'
    | '/hosted/oauth-callback'
    | '/hosted/sign-in'
    | '/hosted/sign-up'
    | '/hosted/verify-email'
    | '/settings/security'
    | '/settings/webhooks'
    | '/tenants/$id'
    | '/tenants/create'
    | '/billing'
    | '/hosted'
    | '/organizations'
    | '/tenants'
    | '/hosted/organization/create'
    | '/hosted/organization/switch'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/login'
    | '/settings'
    | '/users'
    | '/hosted/forgot-password'
    | '/hosted/mfa'
    | '/hosted/oauth-callback'
    | '/hosted/sign-in'
    | '/hosted/sign-up'
    | '/hosted/verify-email'
    | '/settings/security'
    | '/settings/webhooks'
    | '/tenants/$id'
    | '/tenants/create'
    | '/billing/'
    | '/hosted/'
    | '/organizations/'
    | '/tenants/'
    | '/hosted/organization/create'
    | '/hosted/organization/switch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsersRoute: typeof UsersRoute
  HostedForgotPasswordRoute: typeof HostedForgotPasswordRoute
  HostedMfaRoute: typeof HostedMfaRoute
  HostedOauthCallbackRoute: typeof HostedOauthCallbackRoute
  HostedSignInRoute: typeof HostedSignInRoute
  HostedSignUpRoute: typeof HostedSignUpRoute
  HostedVerifyEmailRoute: typeof HostedVerifyEmailRoute
  TenantsIdRoute: typeof TenantsIdRoute
  TenantsCreateRoute: typeof TenantsCreateRoute
  BillingIndexRoute: typeof BillingIndexRoute
  HostedIndexRoute: typeof HostedIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  HostedOrganizationCreateRoute: typeof HostedOrganizationCreateRoute
  HostedOrganizationSwitchRoute: typeof HostedOrganizationSwitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/': {
      id: '/hosted/'
      path: '/hosted'
      fullPath: '/hosted/'
      preLoaderRoute: typeof HostedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/create': {
      id: '/tenants/create'
      path: '/tenants/create'
      fullPath: '/tenants/create'
      preLoaderRoute: typeof TenantsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/hosted/verify-email': {
      id: '/hosted/verify-email'
      path: '/hosted/verify-email'
      fullPath: '/hosted/verify-email'
      preLoaderRoute: typeof HostedVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/sign-up': {
      id: '/hosted/sign-up'
      path: '/hosted/sign-up'
      fullPath: '/hosted/sign-up'
      preLoaderRoute: typeof HostedSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/sign-in': {
      id: '/hosted/sign-in'
      path: '/hosted/sign-in'
      fullPath: '/hosted/sign-in'
      preLoaderRoute: typeof HostedSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/oauth-callback': {
      id: '/hosted/oauth-callback'
      path: '/hosted/oauth-callback'
      fullPath: '/hosted/oauth-callback'
      preLoaderRoute: typeof HostedOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/mfa': {
      id: '/hosted/mfa'
      path: '/hosted/mfa'
      fullPath: '/hosted/mfa'
      preLoaderRoute: typeof HostedMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/forgot-password': {
      id: '/hosted/forgot-password'
      path: '/hosted/forgot-password'
      fullPath: '/hosted/forgot-password'
      preLoaderRoute: typeof HostedForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/organization/switch': {
      id: '/hosted/organization/switch'
      path: '/hosted/organization/switch'
      fullPath: '/hosted/organization/switch'
      preLoaderRoute: typeof HostedOrganizationSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/organization/create': {
      id: '/hosted/organization/create'
      path: '/hosted/organization/create'
      fullPath: '/hosted/organization/create'
      preLoaderRoute: typeof HostedOrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsersRoute: UsersRoute,
  HostedForgotPasswordRoute: HostedForgotPasswordRoute,
  HostedMfaRoute: HostedMfaRoute,
  HostedOauthCallbackRoute: HostedOauthCallbackRoute,
  HostedSignInRoute: HostedSignInRoute,
  HostedSignUpRoute: HostedSignUpRoute,
  HostedVerifyEmailRoute: HostedVerifyEmailRoute,
  TenantsIdRoute: TenantsIdRoute,
  TenantsCreateRoute: TenantsCreateRoute,
  BillingIndexRoute: BillingIndexRoute,
  HostedIndexRoute: HostedIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  HostedOrganizationCreateRoute: HostedOrganizationCreateRoute,
  HostedOrganizationSwitchRoute: HostedOrganizationSwitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
