-- Enforce RLS even for table owners
ALTER TABLE IF EXISTS users FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organizations FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_members FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS keys FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refresh_tokens FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS magic_links FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_verifications FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS password_resets FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS oauth_connections FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rate_limits FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS webhook_endpoints FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS webhook_deliveries FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS billing_plans FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_methods FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usage_records FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS billing_events FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS sso_connections FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sso_domains FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS org_sso_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_domains FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_roles FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenant_branding FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenant_themes FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mfa_credentials FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mfa_backup_codes FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_tokens FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_mappings FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_users FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_groups FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_exports FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_webhooks FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS directory_connections FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS security_policies FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS user_mfa_methods FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_backup_codes FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS scim_audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_group_members FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scim_rate_limits FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS ldap_connections FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ldap_sync_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ldap_user_mappings FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ldap_group_mappings FORCE ROW LEVEL SECURITY;
