name: vault
services:
  - name: vault
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: your-org/vault-server
      tag: latest
    http_port: 3000
    envs:
      - key: VAULT_HOST
        value: 0.0.0.0
      - key: VAULT_PORT
        value: "3000"
      - key: VAULT_METRICS_PORT
        value: "9090"
      - key: VAULT_LOG_LEVEL
        value: info
      - key: VAULT_DATABASE_URL
        value: ""
        type: SECRET
      - key: VAULT_REDIS_URL
        value: ""
        type: SECRET
      - key: VAULT_JWT_SECRET
        value: ""
        type: SECRET
